# Generated by Django 3.1.1 on 2020-09-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('email_id', models.EmailField(max_length=50)),
                ('phone_no', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=30)),
                ('college', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=30)),
                ('div', models.CharField(max_length=30)),
                ('role', models.CharField(default='student', max_length=20)),
            ],
            options={
                'db_table': 'Students',
            },
        ),
    ]
