# Generated by Django 3.1.1 on 2020-10-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aptitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=1000)),
                ('optionA', models.CharField(max_length=500)),
                ('optionB', models.EmailField(max_length=500)),
                ('optionC', models.CharField(max_length=500)),
                ('optionD', models.CharField(max_length=500)),
                ('correct', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Aptitude',
            },
        ),
        migrations.CreateModel(
            name='Technical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=1000)),
                ('optionA', models.CharField(max_length=500)),
                ('optionB', models.EmailField(max_length=500)),
                ('optionC', models.CharField(max_length=500)),
                ('optionD', models.CharField(max_length=500)),
                ('correct', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Technical',
            },
        ),
        migrations.AlterField(
            model_name='students',
            name='role',
            field=models.CharField(max_length=20),
        ),
    ]
