# Generated by Django 3.1.1 on 2020-10-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201002_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listquestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.CharField(max_length=50)),
                ('Question', models.CharField(max_length=1000)),
                ('optionA', models.CharField(max_length=500)),
                ('optionB', models.EmailField(max_length=500)),
                ('optionC', models.CharField(max_length=500)),
                ('optionD', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'Listquestions',
            },
        ),
    ]
