# Generated by Django 3.1.1 on 2020-10-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20201008_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='listquestions',
            name='qtype',
            field=models.CharField(default='apti', max_length=100),
        ),
    ]
